### ISSUE TITLE
No updated compiles for a week+. 

### ISSUE THREAD

**Issue by Barough** [sudo-nautilus/FFmpeg-Builds-Win32#29]
Just wondering whats going on.

**Comment by defisym** [comment]
Seems something wrong with the latest version in build script
![image](https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/assets/55148235/7df182f4-5afe-4241-aa4a-e937088287d7)

And it seems due to that mingw changed repo address
![image](https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/assets/55148235/d053b723-7887-4470-b629-09e728868b32)

IDK if author can check this, it should be super easy to fix

**Comment by Barough** [comment]
Any news regarding the Win32 builds

**Comment by padixa** [comment]
@Barough , @defisym It seems like the author does not maintain this anymore. Could you guys suggest another repository for Win32?

**Comment by defisym** [comment]
I made a fork and it seems to work...partially. 

https://github.com/defisym/FFmpeg-Builds-Win32

**Comment by Barough** [comment]
> I made a fork and it seems to work...partially.
> 
> https://github.com/defisym/FFmpeg-Builds-Win32

That's great :)
Any chance you could make it possible for us to post issues etc over at your fork?

**Comment by defisym** [comment]
> > I made a fork and it seems to work...partially.
> > https://github.com/defisym/FFmpeg-Builds-Win32
> 
> That's great :) Any chance you could make it possible for us to post issues etc over at your fork?

seem that it's disabled for forks by default.
actually, I'm not familiar with actions and build scripts, simply followed the main repo.

**Comment by padixa** [comment]
@defisym That's really great, but latest ffmpeg version should be: v6.1

**Comment by defisym** [comment]
> @defisym That's really great, but latest ffmpeg version should be: v6.1

```
  build_targets:
    name: Build target-variant image
    if: ${{ github.event.inputs.buildOnly != 'true' }}
    needs: build_target_bases
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win32]
        variant: [gpl,lgpl,gpl 4.4,gpl 5.1,gpl 6.0,lgpl 4.4,lgpl 5.1,lgpl 6.0,gpl-shared,lgpl-shared,gpl-shared 4.4,gpl-shared 5.1,gpl-shared 6.0,lgpl-shared 4.4,lgpl-shared 5.1,lgpl-shared 6.0]
```

cause it's not added into variant matrix
I'll try merging main repo to make sure it can build later
